// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package jsonapi

import (
	json "encoding/json"
	snowflake "github.com/gsmcwhirter/discord-bot-lib/v16/snowflake"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson76b0dc3DecodeGithubComGsmcwhirterDiscordBotLibV16Jsonapi(in *jlexer.Lexer, out *GuildMemberResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user":
			if in.IsNull() {
				in.Skip()
				out.User = nil
			} else {
				if out.User == nil {
					out.User = new(UserResponse)
				}
				easyjson76b0dc3DecodeGithubComGsmcwhirterDiscordBotLibV16Jsonapi1(in, out.User)
			}
		case "nick":
			out.Nick = string(in.String())
		case "roles":
			if in.IsNull() {
				in.Skip()
				out.Roles = nil
			} else {
				in.Delim('[')
				if out.Roles == nil {
					if !in.IsDelim(']') {
						out.Roles = make([]string, 0, 4)
					} else {
						out.Roles = []string{}
					}
				} else {
					out.Roles = (out.Roles)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Roles = append(out.Roles, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "joined_at":
			out.JoinedAt = string(in.String())
		case "premium_since":
			out.PremiumSince = string(in.String())
		case "deaf":
			out.Deaf = bool(in.Bool())
		case "mute":
			out.Mute = bool(in.Bool())
		case "RoleSnowflakes":
			if in.IsNull() {
				in.Skip()
				out.RoleSnowflakes = nil
			} else {
				in.Delim('[')
				if out.RoleSnowflakes == nil {
					if !in.IsDelim(']') {
						out.RoleSnowflakes = make([]snowflake.Snowflake, 0, 8)
					} else {
						out.RoleSnowflakes = []snowflake.Snowflake{}
					}
				} else {
					out.RoleSnowflakes = (out.RoleSnowflakes)[:0]
				}
				for !in.IsDelim(']') {
					var v2 snowflake.Snowflake
					v2 = snowflake.Snowflake(in.Uint64())
					out.RoleSnowflakes = append(out.RoleSnowflakes, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76b0dc3EncodeGithubComGsmcwhirterDiscordBotLibV16Jsonapi(out *jwriter.Writer, in GuildMemberResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix[1:])
		if in.User == nil {
			out.RawString("null")
		} else {
			easyjson76b0dc3EncodeGithubComGsmcwhirterDiscordBotLibV16Jsonapi1(out, *in.User)
		}
	}
	{
		const prefix string = ",\"nick\":"
		out.RawString(prefix)
		out.String(string(in.Nick))
	}
	{
		const prefix string = ",\"roles\":"
		out.RawString(prefix)
		if in.Roles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Roles {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"joined_at\":"
		out.RawString(prefix)
		out.String(string(in.JoinedAt))
	}
	{
		const prefix string = ",\"premium_since\":"
		out.RawString(prefix)
		out.String(string(in.PremiumSince))
	}
	{
		const prefix string = ",\"deaf\":"
		out.RawString(prefix)
		out.Bool(bool(in.Deaf))
	}
	{
		const prefix string = ",\"mute\":"
		out.RawString(prefix)
		out.Bool(bool(in.Mute))
	}
	{
		const prefix string = ",\"RoleSnowflakes\":"
		out.RawString(prefix)
		if in.RoleSnowflakes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.RoleSnowflakes {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.Uint64(uint64(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GuildMemberResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson76b0dc3EncodeGithubComGsmcwhirterDiscordBotLibV16Jsonapi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GuildMemberResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson76b0dc3EncodeGithubComGsmcwhirterDiscordBotLibV16Jsonapi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GuildMemberResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson76b0dc3DecodeGithubComGsmcwhirterDiscordBotLibV16Jsonapi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GuildMemberResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson76b0dc3DecodeGithubComGsmcwhirterDiscordBotLibV16Jsonapi(l, v)
}
func easyjson76b0dc3DecodeGithubComGsmcwhirterDiscordBotLibV16Jsonapi1(in *jlexer.Lexer, out *UserResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "username":
			out.Username = string(in.String())
		case "discriminator":
			out.Discriminator = string(in.String())
		case "avatar":
			out.Avatar = string(in.String())
		case "bot":
			out.Bot = bool(in.Bool())
		case "system":
			out.System = bool(in.Bool())
		case "mfa_enabled":
			out.MFAEnabled = bool(in.Bool())
		case "locale":
			out.Locale = string(in.String())
		case "verified":
			out.Verified = bool(in.Bool())
		case "email":
			out.Email = string(in.String())
		case "flags":
			out.Flags = int(in.Int())
		case "premium_type":
			out.PremiumType = int(in.Int())
		case "public_flags":
			out.PublicFlags = int(in.Int())
		case "member":
			if in.IsNull() {
				in.Skip()
				out.Member = nil
			} else {
				if out.Member == nil {
					out.Member = new(GuildMemberResponse)
				}
				(*out.Member).UnmarshalEasyJSON(in)
			}
		case "IDSnowflake":
			out.IDSnowflake = snowflake.Snowflake(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76b0dc3EncodeGithubComGsmcwhirterDiscordBotLibV16Jsonapi1(out *jwriter.Writer, in UserResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"discriminator\":"
		out.RawString(prefix)
		out.String(string(in.Discriminator))
	}
	{
		const prefix string = ",\"avatar\":"
		out.RawString(prefix)
		out.String(string(in.Avatar))
	}
	{
		const prefix string = ",\"bot\":"
		out.RawString(prefix)
		out.Bool(bool(in.Bot))
	}
	{
		const prefix string = ",\"system\":"
		out.RawString(prefix)
		out.Bool(bool(in.System))
	}
	{
		const prefix string = ",\"mfa_enabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.MFAEnabled))
	}
	{
		const prefix string = ",\"locale\":"
		out.RawString(prefix)
		out.String(string(in.Locale))
	}
	{
		const prefix string = ",\"verified\":"
		out.RawString(prefix)
		out.Bool(bool(in.Verified))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix)
		out.Int(int(in.Flags))
	}
	{
		const prefix string = ",\"premium_type\":"
		out.RawString(prefix)
		out.Int(int(in.PremiumType))
	}
	{
		const prefix string = ",\"public_flags\":"
		out.RawString(prefix)
		out.Int(int(in.PublicFlags))
	}
	{
		const prefix string = ",\"member\":"
		out.RawString(prefix)
		if in.Member == nil {
			out.RawString("null")
		} else {
			(*in.Member).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"IDSnowflake\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.IDSnowflake))
	}
	out.RawByte('}')
}
